### PR TITLE
Fixes path handling for imports under windows

### LINKED ISSUE #192: issues with imports under windows
Consider the following:

./app/index.js
./lib/nools/rules/rule1.nools
./lib/nools/rules/rule2.nools

If in index.js, 
```js
nools.compile('../nools/rules/nule1.nools', { /*..etc..*/ })
```

and in rule1.nools,
```
import("./rule2.nools")
```

```
D:\Code\nools-test\cd .\app\
D:\Code\nools-test\app>node index.js
D:\Code\nools-test\node_modules\nools\lib\parser\nools\nool.parser.js:22
                    throw new Error("Invalid " + blockType + " definition \n" + e.message + "; \nstarting at : " + orig);
                    ^

Error: Invalid import definition
ENOENT: no such file or directory, open 'D:\Code\nools-test\app\rule2.nools';
starting at : import("./rule2.nools")

    at parse (D:\Code\nools-test\node_modules\nools\lib\parser\nools\nool.parser.js:22:27)
    at Object.exports.parse (D:\Code\nools-test\node_modules\nools\lib\parser\nools\nool.parser.js:35:5)
    at Object.exports.parseRuleSet (D:\Code\nools-test\node_modules\nools\lib\parser\index.js:15:27)
    at Object.exports.parse (D:\Code\nools-test\node_modules\nools\lib\compile\index.js:144:19)
    at parse (D:\Code\nools-test\node_modules\nools\lib\index.js:24:23)
    at Object.exports.compile (D:\Code\nools-test\node_modules\nools\lib\index.js:58:16)
    at Object.<anonymous> (D:\Code\nools-test\app\index.js:3:7)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
```

Under windows, the path using '/' is not recognized and it will think it's a global import and return the path to the current directory.

### PR DESCRIPTION
**Pull request by tswaters**
- when importing, replace all '/' with '\' so path assertion comes back
  properly

- when going out, ensure '/' are used under windows so requires continue
  to work properly.

- fixes a few tests under windows that were assuming POSIX environment

Fixes #192

### CODE REVIEW

**Comment by vikeen** [comment]
This problem seems like something node would handle under the covers for us. Is there a problem with node's cross-platform file pathing that I'm not aware of?

**Comment by tswaters** [comment]
Sorry, you'll have to bear with me here as I did all of this stuff a few months ago and I haven't really used the project since.  Node's handling is fine, it's just being used weird within nools - mind you there are special considerations like how it parses out its own requires.

There are two bugs here -- one relates to import, which I initially found, ("wtf why doesn't import work... wait, it wants windows slashes?  no no no") and the other relates to importing globals -- I only found globals running the tests and ended up fixing it;  the tests on master currently fail under windows and I'd imagine any global requires in dsl fail under windows (I didn't use them myself).

First, importing rules.

```diff
+    if (process.platform === 'win32') {
+        to = to.replace(/\//g, '\\');
+    }
```

This is to fix the next block:

```js
     if (to.split(pathSep).length === 1) {
         return to;
     }
```

Under windows, the result of the split is always 1 when you import something using standard slashes, e.g.  `import("./myrule")`.  Without this change, `to` is always returned (this is used in callers to identify a slash-less global require like `require('util')`)/  When called like this in a slashy require context, it ends up just concatenating the path to cwd

Second, globals.

```diff
-    return path.resolve(from, to);
+    return path.resolve(from, to).replace(/\\/g, '/');
```

If you include, say,  `global myglobal = require('./my-global')` nools will actually replace this before it gets to ./lib/compile/common.js and runs it through eval.  Under windows, the following code is evaluated:

```
((function(){\n\treturn require('D:\Code\nools-test\nools\rules\global.js')\n})())
```

Which fails - it can't find the module because the backslashes need to be escaped.  Instead of escaping them, though I think it is much easier to modify the resolve function and always return slashes.  Requiring using backslashes does work under windows.

With all that said and done, all of the test changes are to fix up the `path.resolve` calls that always return backslashes under windows to be consistent with what is being returned by nools.

There may be more elegant ways to fix this, but I was under the gun to get a prototype out using nools as its rules engine -- I quickly hacked together this solution and figured I'd share.

**Comment by vikeen** [comment]
> There may be more elegant ways to fix this, but I was under the gun to get a prototype out using nools as its rules engine -- I quickly hacked together this solution and figured I'd share.

No worries. I think we have all been there.

I'm a bit shocked to find out that the tests fail on a windows platform. @doug-martin, I can only assume that nools just doesn't work for windows environments?

**Comment by DevSide** [comment]
Not a good pratice, you should use path.join() instead which takes care of the platform.

**Comment by tswaters** [comment]
@DevSide It does use the path module - this is what causes problems.

When code enters this point the second parameter will be one of the following cases -- 

*  global.  this  should resolve to a file or node_module.

*  import.  this should resolve a file from the directory importing file resides in.  

When the code leaves this function it either [tries to load the file](https://github.com/C2FO/nools/blob/master/lib/parser/nools/tokens.js#L251) (in cases of imports) or will [transpile the code into a require](https://github.com/C2FO/nools/blob/master/lib/parser/nools/tokens.js#L285) (in case of a global)

global case won't work because of backslashes are being returned.  That body string it generates is run through eval eventually and the backslashses need to be escaped once more for it to work properly.  if it's something like `require('util')` it'll work, but requiring a file in the project turns it into an absolute path and it'll blow up because of the unescaped backslashes.

import-loading won't work here because it incorrectly exits early if no os-specific path delimiter is found.   It will be look for the file at the root of the project (or, cwd)

**Comment by DevSide** [comment]
Good for me :+1:

**Comment by DevSide** [comment]
@tswaters, could you rebase on master please

**Comment by DevSide** [comment]
Hm, that's fine jshint pass

**Pull request merged**
